### ISSUE TITLE
Where to get the Gerber Files for the Boards ?

### ISSUE THREAD

**Issue by Snocksman** [DonSuperfo/Superfo-Harlequin-128#1]
Hi !

Nice work ! Where can I get the Gerber Files for the 4A Version of the Board ? I want to build one of these.

**Comment by DonSuperfo** [comment]
Hi,
I will offer at PCBWay.com soon, being update to new revision (minor change)
Thanks!Don  

    On Wednesday, October 5, 2022 at 05:38:22 AM PDT, Snocksman ***@***.***> wrote:  
 
 


Hi !

Nice work ! Where can I get the Gerber Files for the 4A Version of the Board ? I want to build one of these.

**Comment by DonSuperfo** [comment]
Superfo Harlequin 128 Issue 4A - Share Project - PCBWay

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Superfo Harlequin 128 Issue 4A - Share Project - PCBWay

This is a ZX Specrum Clone base on Harlequin by Chris Smith (http://www.zxdesign.info/harlequin.shtml). PCB is t...
 |

 |

 |




    On Wednesday, October 5, 2022 at 05:38:22 AM PDT, Snocksman ***@***.***> wrote:  
 
 


Hi !

Nice work ! Where can I get the Gerber Files for the 4A Version of the Board ? I want to build one of these.
