### ISSUE TITLE
BOM for Issue 4A

### ISSUE THREAD

**Issue by Snocksman** [DonSuperfo/Superfo-Harlequin-128#2]
Hi !

Could you have a look at the BOM for the Issue 4A you posted at PCBway ? I think there are some failures / Chips not marked as option (RS232 / NTSC option).

Here are some examples:
J18 "Header 3 MALE" => Can´t find the Part Number (2553-2112-1X03G00SB-ND) at Digikey.
J12 "Header 4x2" => Part Number ED10541-ND is a 40 PIN IDE Connector at Digikey.
U32 "MAX3232CDR" => Isn´t this Component optional for the RS232 Option ? (And where on the PCB should it be placed ? The only SMD Chip connection on the Board that I can see is for the AD724JR)
U48 "AD724JR" => Isn´t this Component optional for the NTSC Option ?

It would be really cool, if you could have a look at the BOM. I ordered a set of PCBs and would like to order the Chips in the near time.

**Comment by DonSuperfo** [comment]
Hi,
I will take a look, thank you for let me know.You also can get all document from here, this one should be correct.
Superfo 128 Issue 4A - OneDrive (live.com)

Thank,Don
    On Monday, October 24, 2022 at 12:13:08 AM PDT, Snocksman ***@***.***> wrote:  
 
 


Hi !

Could you have a look at the BOM for the Issue 4A you posted at PCBway ? I think there are some failures / Chips not marked as option (RS232 / NTSC option).

Here are some examples:
J18 "Header 3 MALE" => Can´t find the Part Number (2553-2112-1X03G00SB-ND) at Digikey.
J12 "Header 4x2" => Part Number ED10541-ND is a 40 PIN IDE Connector at Digikey.
U32 "MAX3232CDR" => Isn´t this Component optional for the RS232 Option ?
U48 "AD724JR" => Isn´t this Component optional for the NTSC Option ?

It would be really cool, if you could have a look at the BOM. I ordered a set of PCBs and would like to order the Chips in the near time.

**Comment by DonSuperfo** [comment]
J18 part number is 732-5316-NDJ12 is Female header, art Number is ED10541-ND
U32 is an option for RS-232U48 is for composite, both PAL and NTSC
    On Monday, October 24, 2022 at 07:39:46 AM PDT, Don Dindang ***@***.***> wrote:  
 
  Hi,
I will take a look, thank you for let me know.You also can get all document from here, this one should be correct.
Superfo 128 Issue 4A - OneDrive (live.com)

Thank,Don
    On Monday, October 24, 2022 at 12:13:08 AM PDT, Snocksman ***@***.***> wrote:  
 
 


Hi !

Could you have a look at the BOM for the Issue 4A you posted at PCBway ? I think there are some failures / Chips not marked as option (RS232 / NTSC option).

Here are some examples:
J18 "Header 3 MALE" => Can´t find the Part Number (2553-2112-1X03G00SB-ND) at Digikey.
J12 "Header 4x2" => Part Number ED10541-ND is a 40 PIN IDE Connector at Digikey.
U32 "MAX3232CDR" => Isn´t this Component optional for the RS232 Option ?
U48 "AD724JR" => Isn´t this Component optional for the NTSC Option ?

It would be really cool, if you could have a look at the BOM. I ordered a set of PCBs and would like to order the Chips in the near time.
