### ISSUE TITLE
Board 4b

### ISSUE THREAD

**Issue by ghhann** [DonSuperfo/Superfo-Harlequin-128#4]
Is there a link to order the revision 4b of the board.  I did a search on pcbway and could not find a link

Best

**Comment by DonSuperfo** [comment]
I will upload to pcbway in a couple days.ThanksSent from my iPhoneOn Apr 5, 2023, at 11:46 PM, ghhann ***@***.***> wrote:﻿
Is there a link to order the revision 4b of the board.  I did a search on pcbway and could not find a link
Best

**Comment by ghhann** [comment]
Hope all is well.  Looks like you dropped the ide interface between versions 3x and 4x?   Any reason?

Best

**Comment by DonSuperfo** [comment]
Yes, because I add allram mode so no space for the ide.But you ZX Nuvo +2A has ide, you don't need to build ZX Dandanator part.
Best 

    On Sunday, April 30, 2023 at 12:01:46 PM PDT, ghhann ***@***.***> wrote:  
 
 


Hope all is well. Looks like you dropped the ide interface between versions 3x and 4x? Any reason?

Best
