### ISSUE TITLE
Is 4B suitable to be built?

### ISSUE THREAD

**Issue by barbeque** [DonSuperfo/Superfo-Harlequin-128#5]
I noticed in the readme that it says:

> PCB current version is 4A

Does this mean that 4B is still under development, or is it okay to order and build? Thanks!

**Comment by DonSuperfo** [comment]
Hi,It's OK to build 4B, it's final.I will update readme.
Thank you,Don

    On Tuesday, June 4, 2024 at 02:46:08 PM PDT, Mike ***@***.***> wrote:  
 
 


I noticed in the readme that it says:


PCB current version is 4A


Does this mean that 4B is still under development, or is it okay to order and build? Thanks!

**Comment by barbeque** [comment]
Thank you very much! This is a great project, I'm looking forward to building it. Do you have a donation link?
